### ISSUE TITLE
Wallet fixes 1

### ISSUE THREAD

**Issue by h-armless** [enoki-dex/home-page#1]
![image](https://user-images.githubusercontent.com/20886343/173534031-6fe03225-31fe-4e62-8c97-d18422204006.png)
![image](https://user-images.githubusercontent.com/20886343/173537271-0f1e00c0-c278-4f02-a032-a14bdfcb207e.png)

Minting loader can be done here 
![image](https://user-images.githubusercontent.com/20886343/173537416-a550ae17-74e6-4173-9bac-91798868c7ab.png)
https://loading.io/

**Comment by rudyhb** [comment]
done
