### ISSUE TITLE
Swap page fixes 

### ISSUE THREAD

**Issue by h-armless** [enoki-dex/home-page#3]
![image](https://user-images.githubusercontent.com/20886343/173547204-c620f93a-c2a9-454b-b5a2-c6b5c5f75024.png)
![image](https://user-images.githubusercontent.com/20886343/173550212-549f5a6c-74de-4879-bbf8-c3193afb9f70.png)
![image](https://user-images.githubusercontent.com/20886343/173552679-40cde6ec-6d0f-40a4-9826-05377134d544.png)
![image](https://user-images.githubusercontent.com/20886343/173553731-155f9f0d-8154-42f0-b467-48941196e436.png)

**Comment by rudyhb** [comment]
done
