### ISSUE TITLE
Main page fixes 

### ISSUE THREAD

**Issue by h-armless** [enoki-dex/home-page#4]
- Remove color from those links (maybe we need also to just underline on hover them) 
- ![image](https://user-images.githubusercontent.com/20886343/173554976-03e09e19-019d-498e-9782-c29a9a4707e9.png)

- Let's put all icons in features on the middle 
- ![image](https://user-images.githubusercontent.com/20886343/173555399-ceebe6d4-0e67-44b9-8dcd-cca31b84769a.png)

- Can we speed up all the revealing animations on the whole main page? Like twice faster at least ?
- Also we need to speed up button onclick down animation because now it's really slow and I even don't see it

- Increase indents between features on mobile 
- ![image](https://user-images.githubusercontent.com/20886343/173556559-cd1f7fad-4576-4ddd-9c5b-be583bfad160.png)

- ![image](https://user-images.githubusercontent.com/20886343/173570395-2bab15f5-d511-447d-b509-5522177b5691.png)

**Comment by rudyhb** [comment]
done
