### ISSUE TITLE
Wallet popup size/position

### ISSUE THREAD

**Issue by h-armless** [enoki-dex/home-page#5]
- ![image](https://user-images.githubusercontent.com/20886343/174063773-fe56ec8b-3faf-4314-992b-dfe3f12f9290.png)
- buttons are too small on desktop Make them at least 2 times bigger 
- should be the same height as "spaw/pool/trade"

- check mobile version
-  ![image](https://user-images.githubusercontent.com/20886343/174070222-cca508d4-568a-4824-98ea-2e49a6278959.png)

- mobile wallet buttons should look like this 
- ![image](https://user-images.githubusercontent.com/20886343/174070402-f457d107-c1d5-40e5-bcf1-a1bab2ee56df.png)
- and if I click on white space it should close 

- this button white border should be hidden after click on mobile. Also it should be centered. And background section sizes should be bigger maybe (let's have a call, it's so hard to explain in text some stuff)
- ![image](https://user-images.githubusercontent.com/20886343/174069826-f21a3094-01a8-4322-9388-b18c3c18beda.png)

- connect wallet shouldn't be greyed-out, it should open this overlay with 2 buttons to connect (same for desktop)
- also connect wallet on the top should only have underline on hover and click, not after click

**Comment by rudyhb** [comment]
done, except for 
> also connect wallet on the top should only have underline on hover and click, not after click
sorry, above my pay grade
