### ISSUE TITLE
Main page buttons fixes

### ISSUE THREAD

**Issue by h-armless** [enoki-dex/home-page#6]
![image](https://user-images.githubusercontent.com/20886343/174071476-9395427d-ebc3-4d1c-88c1-a267abc35b93.png)

how it should look
![image](https://user-images.githubusercontent.com/20886343/174071533-b18bdf6e-fa0c-4f23-96b0-422ed8ae033e.png)

bigger button font size is 22px

also check this icons positions, seems that they are not centered in both dimensions 
![image](https://user-images.githubusercontent.com/20886343/174072340-5ef59ef8-26b3-41d6-9858-65d059d8b1c3.png)

**Comment by rudyhb** [comment]
ok, I think mostly solved
